### ISSUE TITLE
提案：リスト編集時の全選択機能

### ISSUE THREAD

**Issue by mekanyanko** [Narazaka/vrc_avatar_manager#1]
表示されているアバターを全選択状態にする機能があると非常に嬉しいと思います。

リスト編集時に、アバター名で検索した後などに、現在はクリックで1体ずつ選択する必要があります。
しかし、１つのリストに100体以上該当する場合があり、クリックで追加するのがしんどかったため、Ctrl + Aで「表示されているアバターを全選択状態にする」もしくは同じ機能を実現するボタンが有ると嬉しいなと思いました。

**Comment by Narazaka** [comment]
1.11.0で、リスト式タグ編集時にCtrl+Aで全追加（一部が選択状態である場合）・全削除（全てが選択状態である場合）できるようにしました

**Comment by Narazaka** [comment]
検索ボックスにフォーカス当たってると機能しないのでフォーカスはなしてからCtrl+Aしてくだち
